[package]
name = "gol_sdl"
version = "0.1.0"
authors = ["Carlos Ribeiro <mail@carlosribeiro.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gol = { git = "https://github.com/unleashed/gol" }
sdl2 = "0.31.0"
